repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.10.2
      hooks:
          - id: uv-export
            args: ["--no-hashes", "--output-file=requirements.txt"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.0
      hooks:
          - id: ruff-check
            args: [--fix]

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: "v2.0.4"
      hooks:
          - id: autopep8

#    - repo: local
#      hooks:
#          - id: auto-generate-config
#            name: Auto-generate config
#            entry: uv python ./core/scripts/config_generate.py
#            language: python
#            pass_filenames: false
